#some Env variables
env:
    IMAGE_NAME: "taskyalpa"
  
name: Build And Push

on: 
  pull_request:
    types: [ opened, reopened, synchronize ]
    branches: [ master, main ]
    
jobs:
  Build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@master
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@master
    
    - name: Build and save
      uses: docker/build-push-action@master
      with:
        tags: ${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
        load: true
      
    - name: Login to the registry
      uses: docker/login-action@master
      with:
        username: ${{ secrets.REGISTRY_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
        
    - name: Push
      uses: docker/build-push-action@master
      with:
        push: true
        tags: ${{ secrets.REGISTRY_USER }}/${{ env.IMAGE_NAME }}:latest
